server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${AUTH_DB_URL:jdbc:h2:file:./data/authdb;MODE=MySQL;AUTO_SERVER=TRUE}
    username: ${AUTH_DB_USERNAME:sa}
    password: ${AUTH_DB_PASSWORD:}
    driver-class-name: ${AUTH_DB_DRIVER:org.h2.Driver}
  jpa:
    database-platform: ${AUTH_JPA_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: false

jwt:
  secret: mysecretkeymysecretkeymysecretkeymysecretkey
  expiration-ms: 86400000
